name: Lint and Deploy Todo App

on:
  push:
    branches: [master]

jobs:
  lint:
    name: Lint JavaScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install ESLint
        run: |
          npm install eslint --save-dev
          npx eslint . || true

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy
        uses: actions/deploy-pages@v4
